; Maps configuration file
; File location: $moddir/addons/amxmodx/configs/maps.ini
; To use with Maps Menu plugin

; Add in your mod's maps here
; Delete this file to use mapcycle.txt
de_dust2
cs_office
cs_italy
cs_assault
cs_backalley
cs_militia
cs_siege
cs_havana
cs_747
de_airstrip
de_aztec
de_chateau
de_cbble
de_dust
de_prodigy
de_train
de_storm
de_vertigo
de_torn
de_survivor
de_nuke
de_piranesi
de_inferno
as_oilrig